apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQU44MnZtM3daLzA2RkJUa1NlYVY3dU13RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa01qZzVaVE5pWmpFdFl6UTBNaTAwTkdaakxUbGxaR010TWpJMllqY3lZV1JpTXpFMgpNQjRYRFRFNE1ESXdOekEzTWprMU5Gb1hEVEl6TURJd05qQTRNamsxTkZvd0x6RXRNQ3NHQTFVRUF4TWtNamc1ClpUTmlaakV0WXpRME1pMDBOR1pqTFRsbFpHTXRNakkyWWpjeVlXUmlNekUyTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcXpldXFVNzdkOWlXMlNJc1dodG1CZFg3dEN4NzRTaXI5TEUzV01NVwp4VFVVVDZHNmNNR1IrZG5BNXAyVGFWRytkajZ1eHN2bFdkZW4xQVd1Q0dEKzdkMTNGVEpLQUhCZFp4QkhlSjdSClpiRDNqRTRmMDdsUm1yNjVRRTZzREthUk1xcXl5aU5nU3NQV3JMSm41T1UvVXcxWUJzT1R6YTNPbEkrcnJqS3EKS0ZoUis2a1JRRDBheGtuTzIvRHhHZjVyMlBuY1hWVXdkSUZsbHNOQXhPRFFtQk5kYnk2b051WGN0RkdsaU1mawpTVEh5NHRjejVFQ3dpVjU1M3oyWFk4UFRVZ01vZ3lJVGZoTEttdmtpb3JscDdhZkhkZEJrSHJubUozcmN0K1JtCnJmOFB4TzJtcEZaMlpKV001WjdhTDFVK2ZQbFJZMU40V2NYQVRMc1hOdkdpYlFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpSMWZ0V0JWVExUbmlyZG9uUm11OVVZYXpUUHBOQU9UY3pxNkEwQzNPOUpUVm90TExlWlhxRExGR1REbm12OEhzClEvRXV5czRoalYxaitFei9YamJCSUZSQUFrYTlSOUR2YkJjcmk2NXZDVlZQUDEyRndFT1REUFZaRm5QU3Q4RFcKeTNkbzZQVWpxTnpobW10b1ZTYWFGSTRjWlFtZllHYzh5SFcrQ0JBTnVtWW82N0xFa09Mbml3NXkzVWNvZzk5Mwo1TkMxRkNycW5maHFhbmdKdlRMZ2lLeUxZSU04VjEwamlnQTcySWNDUzBjbG1nL0Z5dnNhaUw4anFhWnlzMjhhCkJXUzdLUThwdlBqWjNWc0c3RzFSbzhLei94WDlpbHNaT3hCdHowclloT0lHN2ZpSUNyNE5XWU16RGUyWjVFYnUKRk03SE9PQzVKUWxMamh0SGoxcEpYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.225.144.151
  name: gke_hanzo-production_us-central1-a_secretpool
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFxTVJRd0VnWURWUVFLRXd0MGFHVXQKY21GdVkyaGxjakVTTUJBR0ExVUVBeE1KWTJGMGRHeGxMV05oTUI0WERURTRNREl3TmpJek1qTTFNMW9YRFRJNApNREl3TkRJek1qTTFNMW93S2pFVU1CSUdBMVVFQ2hNTGRHaGxMWEpoYm1Ob1pYSXhFakFRQmdOVkJBTVRDV05oCmRIUnNaUzFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTFCVUFKUXFMWUEKYzBUK3dRL2YvNElYYVh3RVFIT3g5L2I1d3hBbWNlNU8zMkhoSGI1R2JLSzJXUmNVNVRLa1JjUXR5VlorK0Z2RApHdFRwL09pUUIrdndPSk5EQUQ5Y3M2eVJhYUZUMXhNOE9DaFl3dTYzZVY0T0lPdjZrazhVKysyM1g0K25xakJ5CitDWmFSVjBQOGQwY0pzS0hvZ2twcHB0bEZ3dmtwZzVTUU5QZ0Z3VVUzeEF0SGY0dUFnR1dMSHVRMlNuSmtCM2MKRHlidktYZnpoNXZIeWJBbnBEQ2lmcFM4VzhaRGRjeUZ2N0ErbFBZb2Q1Mm5nM29BaVUyRFhoVTVEZXZmYmZqeQpOTlR6TEd1cFJVVVF1N3Yyd0RYT2JlYnpveC9VZERCZlMzY3NWcnlvemdqdGk1djBoL3RCaGxEMVVlOVo3clRQCkdwOWdJZ0d5eG4wQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUIKQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFINm4xbDF5dk9MQVZtSCtsS3NpOUJrWGpTRlBuVjM3Q1JNZwo3Y25jUVIvZjZsM3RWYVFhblJmdk43NFVFWjQ2OXZYY0NrRTZqOU9kTzdyNVNsZ1hUQ084WHJPNE9TOHFvb2NhCnVQSllMdkZ1NnZaeWcrdzF5QUlsUFEzZ1c5VEtIL1JVV05TT3I4aWJzRGdnYm4rSmdWZDRURngzQjlNQisvdWUKN0RSdVgvZmlwR2YvQXpTaTU5WHFhT1h5eXpaMENwUHd3WTYxVkRVUkRabXdtY2FEdFlOK3hxU0s2WGYrRDY3VwptOTB3L29QT0w0UmR6QkJObDdMa2dyaWI2OWxRNVBqK2tiektwTmtTdDAxSG9VeHduYngwbEphcU5RUGZUTmVECmhQV0hodVF0TUlHaStjR0ZQdnRZRm55cWRhRWlFeUJaTW5oaXcyOHJGYURTQ0FTVWpXST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    server: https://rancher.secretpool.org:8443/k8s/clusters/cluster-6kqss
  name: production
contexts:
- context:
    cluster: gke_hanzo-production_us-central1-a_secretpool
    user: gke_hanzo-production_us-central1-a_secretpool
  name: gke_hanzo-production_us-central1-a_secretpool
- context:
    cluster: production
    user: admin
  name: production
current-context: gke_hanzo-production_us-central1-a_secretpool
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: token-gwzlz:7drwhl7l67hfvtn5bk75wznkbkvp7zkrjnhpjpg8jpb6ttgx556sz5
- name: gke_hanzo-production_us-central1-a_secretpool
  user:
    auth-provider:
      config:
        access-token: ya29.Gl1aBTJL7zNFGzwnPRZNwrCdY7JPrMyAOUunHSHl8VJGcEcfSeBFm8FncMdJ-VxyW26LKYR90_-cBgOtljIWvZbaUF_r-Ljij7Z4HYFBqt5GX1EhHAEDlX9dACyZ_ww
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: 2018-02-07T09:30:10Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
